In [86]:
import pandas as pd
df=pd.read_csv('/content/WELFake_Dataset.csv',error_bad_lines=False,engine='python')

<ipython-input-86-d7c584bfffa7>:2: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df=pd.read_csv('/content/WELFake_Dataset.csv',error_bad_lines=False,engine='python')
Skipping line 329: field larger than field limit (131072)
Skipping line 5242: unexpected end of data
Skipping line 335: Expected 4 fields in line 335, saw 6


In [87]:
df.head()

Unnamed: 0                                              title  \
0          0  LAW ENFORCEMENT ON HIGH ALERT Following Threat...   
1          1                                                NaN   
2          2  UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...   
3          3  Bobby Jindal, raised Hindu, uses story of Chri...   
4          4  SATAN 2: Russia unvelis an image of its terrif...   

                                                text label  
0  No comment is expected from Barack Obama Membe...     1  
1     Did they post their votes for Hillary already?     1  
2   Now, most of the demonstrators gathered last ...     1  
3  A dozen politically active pastors came here f...     0  
4  The RS-28 Sarmat missile, dubbed Satan 2, will...     1

In [88]:
df.shape

(5238, 4)

In [89]:
df.isnull().sum()

Unnamed: 0     0
title         38
text          16
label         15
dtype: int64

In [90]:
df.shape

(5238, 4)

In [91]:
df=df.dropna()

In [92]:
df.head()

Unnamed: 0                                              title  \
0          0  LAW ENFORCEMENT ON HIGH ALERT Following Threat...   
2          2  UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...   
3          3  Bobby Jindal, raised Hindu, uses story of Chri...   
4          4  SATAN 2: Russia unvelis an image of its terrif...   
5          5  About Time! Christian Group Sues Amazon and SP...   

                                                text label  
0  No comment is expected from Barack Obama Membe...     1  
2   Now, most of the demonstrators gathered last ...     1  
3  A dozen politically active pastors came here f...     0  
4  The RS-28 Sarmat missile, dubbed Satan 2, will...     1  
5  All we can say on this one is it s about time ...     1

In [93]:
df['label'].value_counts()

1                                                  2712
0                                                  2474
 is just unbelievably rich from North Sea oil.        1
Name: label, dtype: int64

In [94]:
index_to_drop = df[df['label'].str.strip() == 'is just unbelievably rich from North Sea oil.'].index

# Drop the row(s) with the specified index
df.drop(index_to_drop, inplace=True)

In [95]:
index_to_drop = df[df['label'].str.strip() == 'за участие. Благодарю вас.'].index

# Drop the row(s) with the specified index
df.drop(index_to_drop, inplace=True)

In [96]:
# get the independent feature
x=df.drop('label',axis=1)

In [97]:
y=df['label']

In [98]:
y=y.astype(int)

In [99]:
import tensorflow as tf
from tensorflow.keras.layers import Embedding, LSTM, Bidirectional, Dense
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [100]:
# Vocabulary_size
voc_size=10000

In [101]:
message=x.copy()

In [102]:
message.head()

Unnamed: 0                                              title  \
0          0  LAW ENFORCEMENT ON HIGH ALERT Following Threat...   
2          2  UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...   
3          3  Bobby Jindal, raised Hindu, uses story of Chri...   
4          4  SATAN 2: Russia unvelis an image of its terrif...   
5          5  About Time! Christian Group Sues Amazon and SP...   

                                                text  
0  No comment is expected from Barack Obama Membe...  
2   Now, most of the demonstrators gathered last ...  
3  A dozen politically active pastors came here f...  
4  The RS-28 Sarmat missile, dubbed Satan 2, will...  
5  All we can say on this one is it s about time ...

In [103]:
message.reset_index(inplace=True)

In [104]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [105]:
import nltk
import re
from nltk.corpus import stopwords
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [106]:
# Dataset Preprocessing
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
corpus = []
for i in range(0, len(message['title'])):
    review = re.sub('[^a-zA-Z]', ' ', message['title'][i])
    review = review.lower()
    review = review.split()
    review = [lemmatizer.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [107]:
corpus

['law enforcement high alert following threat cop white blacklivesmatter fyf terrorist video',
 'unbelievable obama attorney general say charlotte rioter peaceful protester home state north carolina video',
 'bobby jindal raised hindu us story christian conversion woo evangelicals potential bid',
 'satan russia unvelis image terrifying new supernuke western world take notice',
 'time christian group sue amazon splc designation hate group',
 'dr ben carson targeted irs never audit spoke national prayer breakfast',
 'house intel chair trump russia fake story evidence anything video',
 'sport bar owner ban nfl game show true american sport like speak rural america video',
 'latest pipeline leak underscore danger dakota access pipeline',
 'gop senator smacked punchable alt right nazi internet',
 'may brexit offer would hurt cost eu citizen eu parliament',
 'schumer call trump appoint official oversee puerto rico relief',
 'watch hilarious ad call question health aging clinton crime family 

In [108]:
 onehot_rpr=[one_hot(words,voc_size) for words in corpus]

In [109]:
onehot_rpr

[[2254, 8825, 6169, 8316, 6393, 3911, 3553, 4444, 3845, 845, 4888, 754],
 [9137,
  2753,
  4078,
  184,
  8182,
  8870,
  617,
  2537,
  5476,
  4265,
  5933,
  2108,
  2876,
  754],
 [5110, 3035, 5900, 2612, 9041, 8845, 5859, 6789, 6375, 8607, 7124, 5561],
 [2609, 5178, 3424, 4496, 2505, 4782, 1004, 3744, 7633, 5547, 2602],
 [4220, 5859, 7064, 4904, 3652, 901, 6621, 1325, 7064],
 [2237, 9781, 7117, 2521, 5077, 2778, 1813, 6437, 4597, 8013, 5375],
 [9915, 6665, 870, 8240, 5178, 5581, 8845, 2954, 5613, 754],
 [3998,
  2300,
  8458,
  432,
  3318,
  3599,
  1390,
  7611,
  9527,
  3998,
  3936,
  4309,
  80,
  6408,
  754],
 [7613, 2709, 4494, 1372, 4638, 2631, 9188, 2709],
 [7388, 3585, 4432, 1081, 1574, 3336, 7948, 7223],
 [5116, 1417, 1899, 4217, 7954, 9770, 1469, 5060, 1469, 6385],
 [119, 4583, 8240, 5483, 2045, 7382, 1444, 251, 572],
 [9840, 9783, 8576, 4583, 6111, 6243, 558, 1518, 9091, 6578, 2914],
 [9136, 4527, 7596, 3555, 5148, 5791, 5696, 4691, 8242, 2592],
 [2114, 7161, 955, 7

In [110]:
# Embedding Representation

In [111]:
sent_length = 40
embedded=pad_sequences(onehot_rpr, padding='pre',maxlen=sent_length)

In [112]:
embedded

array([[   0,    0,    0, ...,  845, 4888,  754],
       [   0,    0,    0, ..., 2108, 2876,  754],
       [   0,    0,    0, ..., 8607, 7124, 5561],
       ...,
       [   0,    0,    0, ..., 5903,   94, 2858],
       [   0,    0,    0, ..., 7908, 2732, 1983],
       [   0,    0,    0, ..., 8010, 8557, 1754]], dtype=int32)

In [114]:
from tensorflow.keras.layers import Dropout
from tensorflow.keras.regularizers import l2
embedding_vector_features=80
# creating model
model = Sequential()
model.add(Embedding(voc_size, embedding_vector_features, input_length=sent_length))
model.add(Bidirectional(LSTM(100, kernel_regularizer=l2(0.01))))  # Add L2 regularization to LSTM layer
model.add(Dropout(0.3))
model.add(Dense(1, activation='sigmoid', kernel_regularizer=l2(0.01)))  # Add L2 regularization to Dense layer

In [115]:

model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 40, 80)            800000    
                                                                 
 bidirectional_2 (Bidirecti  (None, 200)               144800    
 onal)                                                           
                                                                 
 dropout_2 (Dropout)         (None, 200)               0         
                                                                 
 dense_2 (Dense)             (None, 1)                 201       
                                                                 
Total params: 945001 (3.60 MB)
Trainable params: 945001 (3.60 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [116]:
import numpy as np
x_final = np.array(embedded)
y_final = np.array(y)

In [117]:
x.shape

(5186, 3)

In [118]:
y.shape

(5186,)

In [119]:
# train test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_final,y_final,test_size=0.3,random_state=10)

In [120]:
early_stopping= tf.keras.callbacks.EarlyStopping(
    monitor="val_loss",
    min_delta=0.001,
    patience=20,
    verbose=0,
    mode="auto",
    baseline=None,
    restore_best_weights=True,
    start_from_epoch=0,
)

In [121]:
# Model Training
model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=100, batch_size=32, callbacks=early_stopping)

Epoch 1/100
114/114 [==============================] - 15s 95ms/step - loss: 1.4318 - accuracy: 0.6152 - val_loss: 0.6921 - val_accuracy: 0.7391
Epoch 2/100
114/114 [==============================] - 8s 73ms/step - loss: 0.5054 - accuracy: 0.8325 - val_loss: 0.5047 - val_accuracy: 0.7905
Epoch 3/100
114/114 [==============================] - 10s 84ms/step - loss: 0.3378 - accuracy: 0.8939 - val_loss: 0.5028 - val_accuracy: 0.7969
Epoch 4/100
114/114 [==============================] - 9s 78ms/step - loss: 0.2561 - accuracy: 0.9303 - val_loss: 0.5204 - val_accuracy: 0.8014
Epoch 5/100
114/114 [==============================] - 8s 74ms/step - loss: 0.1842 - accuracy: 0.9537 - val_loss: 0.7787 - val_accuracy: 0.7834
Epoch 6/100
114/114 [==============================] - 8s 74ms/step - loss: 0.2719 - accuracy: 0.9623 - val_loss: 0.6110 - val_accuracy: 0.8014
Epoch 7/100
114/114 [==============================] - 10s 84ms/step - loss: 0.1592 - accuracy: 0.9771 - val_loss: 0.7334 - val_accura

In [122]:
y_pred = model.predict(x_test)

49/49 [==============================] - 2s 15ms/step


In [123]:
y_pred = np.where(y_pred>0.5,1,0)

In [124]:
y_pred

array([[0],
       [1],
       [0],
       ...,
       [0],
       [1],
       [1]])

In [125]:
from sklearn.metrics import accuracy_score, confusion_matrix
print('accuracy score of model is:',accuracy_score(y_test,y_pred))

accuracy score of model is: 0.7969151670951157


In [126]:
print(confusion_matrix(y_test,y_pred))

[[619 129]
 [187 621]]
