In [1]:
import pandas as pd
import re
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

In [8]:
df=pd.read_csv(r'/content/IMDB Dataset.csv',error_bad_lines=False,engine='python')

<ipython-input-8-05fd995811be>:1: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df=pd.read_csv(r'/content/IMDB Dataset.csv',error_bad_lines=False,engine='python')
Skipping line 771: unexpected end of data


In [9]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [10]:
df.shape

(769, 2)

In [11]:
# Checking if there is any nan values
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [12]:
df['sentiment'].value_counts()

negative    396
positive    373
Name: sentiment, dtype: int64

In [13]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [14]:
lemmatizer = WordNetLemmatizer()
stop_words = stopwords.words('english')


In [15]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [16]:
# Text Preprocessing
#converting to lower case
df["review"] = df["review"].apply(lambda x: x.lower())
#removing everything instead of 0-9, a-z, A-Z
df["review"] = df["review"].apply(lambda x: re.sub("[^0-9a-zA-Z]"," ", x))
#removing html tags
clean_html = re.compile('<.*?>')
df["review"] = df["review"].apply(lambda x: re.sub(clean_html, "", x))
#lemmatizing
df["review"] = df["review"].apply(lambda x: lemmatizer.lemmatize(x))
#removing extra white spaces
df["review"] = df["review"].apply(lambda x: re.sub(" +"," ", x) )

In [17]:
df.head()

review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production br br the filmin...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there s a family where a little boy ...  negative
4  petter mattei s love in the time of money is a...  positive

In [18]:
df.head()

review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production br br the filmin...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there s a family where a little boy ...  negative
4  petter mattei s love in the time of money is a...  positive

In [19]:
# splitting the dataset
x = df.iloc[:,0]
y = df.drop('review', axis=1)

In [20]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y=le.fit_transform(y)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [21]:
x

0      one of the other reviewers has mentioned that ...
1      a wonderful little production br br the filmin...
2      i thought this was a wonderful way to spend ti...
3      basically there s a family where a little boy ...
4      petter mattei s love in the time of money is a...
                             ...                        
764    i first saw this film when i was about 8 years...
765    this film can t make up its mind whether its m...
766    why o why did i pick this one up well i needed...
767    only a very small child could overlook the abs...
768    our teacher showed us this movie in first grad...
Name: review, Length: 769, dtype: object

In [22]:
y

array([1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,

In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer(stop_words=stop_words)
x=tf.fit_transform(x)

In [24]:
# train test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=42)

In [25]:
# Multi-nomial naive bayes
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()

In [26]:
nb.fit(x_train,y_train)
y_pred=nb.predict(x_test)

In [27]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [28]:
print('Accuracy score of model:',accuracy_score(y_test,y_pred))

Accuracy score of model: 0.7616580310880829


In [29]:
print(confusion_matrix(y_test,y_pred))

[[91 20]
 [26 56]]


In [32]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(x_train,y_train)
y_pred = lr.predict(x_test)

In [36]:
print('Accuracy score of model:',accuracy_score(y_test,y_pred))

Accuracy score of model: 0.7512953367875648


In [34]:
print(confusion_matrix(y_test,y_pred))

[[77 34]
 [15 67]]


In [35]:
# Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()
rfc.fit(x_train,y_train)
y_pred=rfc.predict(x_test)

In [37]:
print('Accuracy score of model:',accuracy_score(y_test,y_pred))

Accuracy score of model: 0.7512953367875648


In [39]:
# Grid search Cv
from sklearn.model_selection import GridSearchCV
random_search = {
    'n_estimators':[50,100,200,300,400,600,800],
    'criterion':['gini','entropy'],
    'max_depth':[2,5,8,10,12,15],
    'min_samples_split':[2,4,6,8,10]
}
grid_search = GridSearchCV(rfc,random_search,verbose=1, n_jobs=-1,cv=5)

grid_search.fit(x_train,y_train)

print(grid_search.best_estimator_)

Fitting 5 folds for each of 420 candidates, totalling 2100 fits
RandomForestClassifier(criterion='entropy', max_depth=10, n_estimators=400)


In [45]:
rfc=RandomForestClassifier(criterion='entropy', max_depth=10, n_estimators=400,max_features='sqrt')
rfc.fit(x_train,y_train)
y_pred=rfc.predict(x_test)

In [46]:
print('Accuracy score of model:',accuracy_score(y_test,y_pred))

Accuracy score of model: 0.7305699481865285


In [54]:
import xgboost as xgb
xgb = xgb.XGBClassifier()
xgb.fit(x_train,y_train)
y_pred=xgb.predict(x_test)

In [55]:
print('Accuracy score of model:',accuracy_score(y_test,y_pred))

Accuracy score of model: 0.7202072538860104
